[package]
name = "test_bit_quality"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
rand = "0.8.5"
rayon = "1.10.0"
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.119"
statrs = "0.17.1"
