[package]
name = "test_bit_quality"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
ccm = "0.5.0"
chrono = "0.4.38"
cliclack = "0.3.1"
cmac = "0.7.2"
rand = "0.8.5"
rayon = "1.10.0"
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.119"
statrs = "0.17.1"
